name: Build Custom APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"


      - name: Check Secret
        run: |

          if [ -z "${GH_TOKEN}" ]; then
            echo "GH_TOKEN not found"
            exit 1
          fi

          echo "GH_TOKEN loaded successfully"

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


      - name: Check HTML
        run: |

          echo "Checking website files..."

          if [ ! -f "www/index.html" ]; then
            echo "ERROR: www/index.html not found"
            exit 1
          fi

          echo "HTML OK"


      - name: Create package.json
        run: |

          cat > package.json <<'EOF'
          {
            "name": "apk-builder",
            "version": "1.0.0",
            "private": true,
            "dependencies": {
              "@capacitor/core": "^7.4.3"
            },
            "devDependencies": {
              "@capacitor/cli": "^7.4.3",
              "@capacitor/android": "^7.4.3"
            }
          }
          EOF


      - name: Install
        run: |

          npm install


      - name: Create Capacitor Config
        run: |

          cat > capacitor.config.json <<'EOF'
          {
            "appId": "com.generated.app",
            "appName": "Generated APK",
            "webDir": "www"
          }
          EOF


      - name: Add Android
        run: |

          npx cap add android


      - name: Sync Android
        run: |

          npx cap sync android


      - name: Build APK
        working-directory: android
        run: |

          chmod +x gradlew

          ./gradlew assembleDebug


      - name: Prepare Files
        run: |

          mkdir output

          cp android/app/build/outputs/apk/debug/app-debug.apk output/app.apk

          cd output

          zip app.zip app.apk


      - name: Upload APK
        uses: actions/upload-artifact@v4

        with:

          name: APK

          path: output/app.apk


      - name: Upload ZIP
        uses: actions/upload-artifact@v4

        with:

          name: APK-ZIP

          path: output/app.zip
          # updated
